### PR TITLE
add note on styles

### LINKED ISSUE #37: provide guidance on block styles
There are some narrative block styles to be used

- `dragon`
- `stu-note`
- `note-to-balloters`
- `modified-content`
- `new-content`
- `feedback`

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #37

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@lmckenzi @grahamegrieve

**Comment by costateixeira** [comment]
I think this is a good addition but would prefer to keep the dragon in the colors page as well, as that page shows the colors that can be changed. So, keep the additions, remove the deletions.

**Comment by JohnMoehrke** [comment]
> I think this is a good addition but would prefer to keep the dragon in the colors page as well, as that page shows the colors that can be changed. So, keep the additions, remove the deletions.

I am not strongly needing to change the colors.md. I changed it so as to focus the reader on where to find the styles. Leaving them on the colors.md page for the above reason, would really need to have guidance to the reader that that is why they are here. It is not clear to me that this is the reason to have these two styles mentioned on the colors.md page.

**Comment by JohnMoehrke** [comment]
@lmckenzi can you review and approve?

**Review by lmckenzi — APPROVED** [review]

**Comment by JohnMoehrke** [comment]
@lmckenzi could you merge? I don't have rights to do this... or you could give me rights.

**Pull request merged**
